package view;

import java.awt.*;

/**
 * Interface for a hook that gets called immediately after a RoomView is processed
 * in MazeView, allowing for this hook to alter the resulting image of the room.
 *
 * @author Shane Menzies
 * @version 12/3/24
 */
public interface RoomViewHook {
    /**
     * Perform some action after the image for the provided RoomView is processed,
     * which can be edited using the provided Graphics2D handle.
     *
     * @param theGraphics Graphics2D Handle to the image generated by RoomView.
     * @param theRoom The RoomView which just generated the image.
     */
    void doHook(Graphics2D theGraphics, RoomView theRoom);
}